/* Van Gogh — Paper-Level Neural Preserving demo (v5)
 *
 * What makes this "paper level":
 *   The motion you see is not a hand-animated effect. A PyTorch pipeline
 *   (all models real, cited in the README) precomputes a 16-phase periodic
 *   animation cycle of the painting, and RAFT (Teed & Deng, ECCV 2020)
 *   MEASURES the per-pixel displacement of every phase back to the original
 *   canvas. This player plays those measured fields back, blended between
 *   adjacent phases — a looping, time-varying neural motion field.
 *
 * Offline CV assets (generated by cv_pipeline/, all torch):
 *   cv_pipeline/assets/depth/depth_midas_small.png   MiDaS v2.1 small depth
 *   cv_pipeline/assets/flow/flow_raft_phases.png     RAFT-small, 4x4 atlas
 *     16 phases of a periodic cycle; tile k = displacement of phase k back to
 *     the original painting. flow_px = (texel.rg - 0.5) * 64.0
 *   cv_pipeline/assets/layers/layer_0..5_*.png        MobileSAM segmentation
 *
 * Rendering modes:
 *   NEURAL   — all assets loaded: RAFT phase-cycle playback + MiDaS depth
 *              parallax + star twinkle + village window flicker + moon glow
 *   FALLBACK — any asset missing: whole-canvas procedural waves (aspect-correct,
 *              clearly animated) so the page never degrades to a static image
 *
 * Preserving: the original pixels are only ever RE-SAMPLED (warped), never
 * repainted — colors, brush strokes and composition stay exactly Van Gogh's.
 */
(function () {
  'use strict';

  var IMG_W = 1280, IMG_H = 1014;        // source painting resolution
  var FLOW_DECODE = 64.0;                // flow_px = (texel.rg - 0.5) * 64
  var CYCLE = 14.0;                      // seconds per 16-phase motion cycle
  var FLOW_AMP = 1.15;                   // RAFT playback gain (1.0 = measured)
  var PARALLAX = 0.05;                   // pointer parallax strength
  var LAYER_FILES = [
    'cv_pipeline/assets/layers/layer_0_sky.png',
    'cv_pipeline/assets/layers/layer_1_moon.png',
    'cv_pipeline/assets/layers/layer_2_stars.png',
    'cv_pipeline/assets/layers/layer_3_cypress.png',
    'cv_pipeline/assets/layers/layer_4_village.png',
    'cv_pipeline/assets/layers/layer_5_mountains.png'
  ];

  /* ---------- renderer / scene ---------- */
  var canvas = document.querySelector('#c');
  var renderer = new THREE.WebGLRenderer({ canvas: canvas, antialias: true });
  renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
  var scene = new THREE.Scene();
  var camera = new THREE.OrthographicCamera(-1, 1, 1, -1, 0, 10);

  var uniforms = {
    uTex:          { value: null },
    uDepth:        { value: null },
    uFlowAtlas:    { value: null },
    uL0: { value: null }, uL1: { value: null }, uL2: { value: null },
    uL3: { value: null }, uL4: { value: null }, uL5: { value: null },
    uTime:          { value: 0 },
    uMouse:         { value: new THREE.Vector2(0.5, 0.5) },
    uScreenAspect:  { value: 1.0 },
    uImageAspect:   { value: IMG_W / IMG_H },
    uAssets:        { value: 0.0 },    // 1 = neural mode ready
    uFlowAmp:       { value: FLOW_AMP },
    uParallax:      { value: PARALLAX },
    uFlowDecode:    { value: FLOW_DECODE },
    uCycle:         { value: CYCLE },
    uImgSize:       { value: new THREE.Vector2(IMG_W, IMG_H) }
  };

  var material = new THREE.ShaderMaterial({
    uniforms: uniforms,
    vertexShader: [
      'varying vec2 vUv;',
      'void main() { vUv = uv; gl_Position = vec4(position, 1.0); }'
    ].join('\n'),
    fragmentShader: [
      'precision highp float;',
      'uniform sampler2D uTex, uDepth, uFlowAtlas;',
      'uniform sampler2D uL0, uL1, uL2, uL3, uL4, uL5;',
      'uniform float uTime, uScreenAspect, uImageAspect, uAssets;',
      'uniform float uFlowAmp, uParallax, uFlowDecode, uCycle;',
      'uniform vec2 uMouse, uImgSize;',
      'varying vec2 vUv;',

      /* Letterbox (contain) mapping: the FULL painting always stays visible
         and undistorted; leftover viewport area becomes black bars. */
      'vec3 containUV(vec2 uv) {',
      '  if (uScreenAspect > uImageAspect) {',
      '    float f = uImageAspect / uScreenAspect;',
      '    float x = (uv.x - 0.5) / f + 0.5;',
      '    return vec3(x, uv.y, step(0.0, x) * step(x, 1.0));',
      '  } else {',
      '    float f = uScreenAspect / uImageAspect;',
      '    float y = (uv.y - 0.5) / f + 0.5;',
      '    return vec3(uv.x, y, step(0.0, y) * step(y, 1.0));',
      '  }',
      '}',

      /* Sample one phase tile of the RAFT flow atlas (4x4 grid, tile k = phase
         k; row 0 of the PNG is the TOP row, three.js flipY makes v grow up,
         so PNG row r maps to atlas row (3 - r) from the bottom). A half-texel
         inset prevents bilinear bleeding from neighboring tiles. */
      'vec2 flowPx(vec2 t, float idx) {',
      '  float tx = mod(idx, 4.0);',
      '  float rowB = 3.0 - floor(idx / 4.0);',
      '  vec2 tt = clamp(t, vec2(0.0016, 0.0021), vec2(0.9984, 0.9979));',
      '  vec2 auv = (vec2(tx, rowB) + tt) / 4.0;',
      '  vec3 c = texture2D(uFlowAtlas, auv).rgb;',
      '  return (c.rg - 0.5) * uFlowDecode;',
      '}',

      'void main() {',
      '  vec3 m = containUV(vUv);',
      '  vec2 uv = clamp(m.xy, 0.0, 1.0);',
      '  float inside = m.z;',

      /* gentle global breathing (subtle zoom, both modes) */
      '  uv = (uv - 0.5) * (1.0 - 0.008 * sin(uTime * 0.45)) + 0.5;',

      '  vec3 col;',
      '  if (uAssets >= 0.5) {',
      /* ---- NEURAL MODE ---- */
      '    float wMoon = texture2D(uL1, uv).r;',
      '    float wStar = texture2D(uL2, uv).r;',
      '    float wVil  = texture2D(uL4, uv).r;',

      /* MiDaS depth: pointer parallax + slow autonomous drift */
      '    float depth = texture2D(uDepth, uv).r;',
      '    vec2 par = (uMouse - 0.5) * (depth - 0.35) * uParallax;',
      '    par += vec2(sin(uTime * 0.31), cos(uTime * 0.27)) * 0.016 * depth;',

      /* RAFT phase-cycle playback: blend the two nearest measured phases */
      '    float f16 = fract(uTime / uCycle) * 16.0;',
      '    float k = floor(f16);',
      '    float a = fract(f16);',
      '    vec2 bpx = mix(flowPx(uv, k), flowPx(uv, mod(k + 1.0, 16.0)), a);',
      '    vec2 buv = bpx * uFlowAmp / uImgSize;',

      /* micro brushstroke shimmer (keeps paint texture alive at cycle ebb) */
      '    vec2 micro = vec2(sin(uv.y * 90.0 + uTime * 1.7),',
      '                      cos(uv.x * 80.0 - uTime * 1.3)) * 0.0004;',

      '    vec2 uvN = uv + par + buv + micro;',
      '    col = texture2D(uTex, clamp(uvN, 0.0, 1.0)).rgb;',

      /* star twinkle (luminance only — preserving) */
      '    col += wStar * (0.08 + 0.08 * sin(uTime * 2.6 + uv.x * 37.0));',
      /* village window flicker (bright pixels only) */
      '    float lum = dot(col, vec3(0.299, 0.587, 0.114));',
      '    col += wVil * smoothstep(0.30, 0.65, lum)',
      '         * 0.14 * (0.5 + 0.5 * sin(uTime * 3.7 + uv.x * 211.0));',
      /* moon glow breathing */
      '    col += wMoon * 0.05 * (0.5 + 0.5 * sin(uTime * 0.9 + 1.0));',
      '  } else {',
      /* ---- FALLBACK MODE (whole-canvas procedural, no assets) ---- */
      '    vec2 w;',
      '    w.x = sin(uv.y * 24.0 + uTime * 1.2) * 0.0028',
      '        + sin(uv.y * 7.0  - uTime * 0.7) * 0.0018;',
      '    w.y = cos(uv.x * 20.0 + uTime * 0.9) * 0.0016',
      '        + sin(uv.x * 5.0  + uTime * 0.5) * 0.0010;',
      '    col = texture2D(uTex, clamp(uv + w, 0.0, 1.0)).rgb;',
      '    col *= 1.0 + 0.02 * sin(uTime * 0.8);',
      '  }',

      '  gl_FragColor = vec4(col * inside, 1.0);',  // bars stay pure black
      '}'
    ].join('\n')
  });

  scene.add(new THREE.Mesh(new THREE.PlaneGeometry(2, 2), material));

  /* ---------- status badge (self-fading, deployment self-check) ---------- */
  var badge = document.createElement('div');
  badge.id = 'vg-badge';
  Object.assign(badge.style, {
    position: 'fixed', left: '12px', bottom: '12px', zIndex: '10',
    fontFamily: 'ui-monospace, SFMono-Regular, Consolas, monospace',
    fontSize: '11px', lineHeight: '1.55', padding: '6px 10px',
    borderRadius: '4px', color: '#fff', background: 'rgba(0,0,0,0.55)',
    borderLeft: '3px solid #888', pointerEvents: 'none',
    maxWidth: '70vw', opacity: '0', transition: 'opacity 1.2s ease'
  });
  document.body.appendChild(badge);

  function showBadge(neuralOn, detail) {
    badge.style.borderLeftColor = neuralOn ? '#4ade80' : '#fbbf24';
    badge.innerHTML = neuralOn
      ? 'NEURAL PIPELINE: ACTIVE<br><span style="opacity:.75">' +
        'MiDaS depth + RAFT 16-phase flow cycle + 6 SAM layers</span>'
      : 'NEURAL PIPELINE: NOT LOADED<br><span style="opacity:.75">' +
        'procedural fallback active — ' + detail + '</span>';
    badge.style.opacity = '1';
    setTimeout(function () { badge.style.opacity = '0'; }, 9000);
  }

  /* ---------- asset loading with failure tracking ---------- */
  var failedFiles = [];
  var manager = new THREE.LoadingManager(
    function () {                                   // onLoad: queue settled
      var neuralOn = failedFiles.length === 0;
      uniforms.uAssets.value = neuralOn ? 1.0 : 0.0;
      window.__vanGoghStatus = { mode: neuralOn ? 'neural' : 'fallback',
                                 failed: failedFiles.slice() };
      if (neuralOn) {
        console.info('[VanGogh] neural mode active: depth + 16-phase RAFT flow atlas + 6 layers loaded');
      } else {
        console.warn('[VanGogh] neural assets missing (' + failedFiles.length +
                     '), running procedural fallback. Missing:', failedFiles);
      }
      showBadge(neuralOn, failedFiles.length + ' asset file(s) missing');
    },
    undefined,
    function (url) { failedFiles.push(url); }       // onError: record the URL
  );
  var loader = new THREE.TextureLoader(manager);

  function dataTex(url) {   // data textures: no mipmaps, clamp edges, linear filter
    var t = loader.load(url);
    t.generateMipmaps = false;
    t.minFilter = THREE.LinearFilter;
    t.magFilter = THREE.LinearFilter;
    t.wrapS = t.wrapT = THREE.ClampToEdgeWrapping;
    return t;
  }

  uniforms.uTex.value = loader.load('starry-night.jpg');
  uniforms.uTex.value.colorSpace = THREE.SRGBColorSpace;
  uniforms.uDepth.value = dataTex('cv_pipeline/assets/depth/depth_midas_small.png');
  uniforms.uFlowAtlas.value = dataTex('cv_pipeline/assets/flow/flow_raft_phases.png');
  ['uL0', 'uL1', 'uL2', 'uL3', 'uL4', 'uL5'].forEach(function (k, i) {
    uniforms[k].value = dataTex(LAYER_FILES[i]);
  });

  /* ---------- interaction ---------- */
  var mouseTarget = new THREE.Vector2(0.5, 0.5);
  window.addEventListener('pointermove', function (e) {
    mouseTarget.set(e.clientX / window.innerWidth, 1.0 - e.clientY / window.innerHeight);
  }, { passive: true });

  function resize() {
    var w = window.innerWidth, h = window.innerHeight;
    renderer.setSize(w, h, false);
    uniforms.uScreenAspect.value = w / h;
  }
  window.addEventListener('resize', resize);
  resize();

  /* ---------- render loop ---------- */
  var t0 = performance.now();
  (function animate(now) {
    uniforms.uTime.value = (now - t0) * 0.001;
    uniforms.uMouse.value.lerp(mouseTarget, 0.08);   // smooth pointer
    renderer.render(scene, camera);
    requestAnimationFrame(animate);
  })(t0);
})();
