/* Van Gogh Neural Original Preserving — neural pipeline consumer
 *
 * Offline CV assets (generated by cv_pipeline/scripts, consumed here):
 *   cv_pipeline/assets/depth/depth_midas_small.png  — MiDaS v2.1 small depth map
 *   cv_pipeline/assets/flow/flow_raft_rgb.png        — RAFT-small optical flow
 *     (v4: comprehensive field — sky swirls + current, cypress sway,
 *      village / mountain drift; every region carries motion)
 *   cv_pipeline/assets/layers/layer_0..5_*.png       — MobileSAM segmentation masks
 *
 * Rendering modes:
 *   NEURAL   — all assets loaded: depth parallax + flow-driven advection with
 *              per-layer temporal phase + procedural wave blend (guarantees the
 *              whole canvas moves) + star twinkle + village window flicker
 *              + moon glow breathing
 *   FALLBACK — any asset missing: procedural swirl, aspect-correct and clearly
 *              animated, so the page never degrades to a static image
 *
 * A small status badge (bottom-left, fades out after a few seconds) tells you
 * which mode is active — if you see the orange one after deploying, the
 * cv_pipeline folder did not make it into your repository.
 */
(function () {
  'use strict';

  var IMG_W = 1280, IMG_H = 1014;        // source painting resolution
  var FLOW_DECODE = 32.0;                 // flow_px = (texel.rg - 0.5) * 32
  var LAYER_FILES = [
    'cv_pipeline/assets/layers/layer_0_sky.png',
    'cv_pipeline/assets/layers/layer_1_moon.png',
    'cv_pipeline/assets/layers/layer_2_stars.png',
    'cv_pipeline/assets/layers/layer_3_cypress.png',
    'cv_pipeline/assets/layers/layer_4_village.png',
    'cv_pipeline/assets/layers/layer_5_mountains.png'
  ];
  var FLOW_AMP = 6.0;                    // neural flow advection gain
  var PARALLAX = 0.05;                   // pointer parallax strength
  // Per-layer temporal phase offsets (radians): regions undulate out of sync,
  // so the painting never moves in rigid lockstep.
  var PHASE_A = [0.0, 1.4, 2.8];         // sky, moon, stars
  var PHASE_B = [4.2, 5.6, 7.0];         // cypress, village, mountains

  /* ---------- renderer / scene ---------- */
  var canvas = document.querySelector('#c');
  var renderer = new THREE.WebGLRenderer({ canvas: canvas, antialias: true });
  renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
  var scene = new THREE.Scene();
  var camera = new THREE.OrthographicCamera(-1, 1,1,-1, 0, 10);

  var uniforms = {
    uTex:          { value: null },
    uDepth:        { value: null },
    uFlow:         { value: null },
    uL0: { value: null }, uL1: { value: null }, uL2: { value: null },
    uL3: { value: null }, uL4: { value: null }, uL5: { value: null },
    uTime:          { value: 0 },
    uMouse:         { value: new THREE.Vector2(0.5, 0.5) },
    uScreenAspect:  { value: 1.0 },
    uImageAspect:   { value: IMG_W / IMG_H },
    uAssets:        { value: 0.0 },    // 1 = neural mode ready
    uFlowAmp:       { value: FLOW_AMP },
    uParallax:      { value: PARALLAX },
    uFlowDecode:    { value: FLOW_DECODE },
    uImgSize:       { value: new THREE.Vector2(IMG_W, IMG_H) },
    uPhaseA:        { value: new THREE.Vector3(PHASE_A[0], PHASE_A[1], PHASE_A[2]) },
    uPhaseB:        { value: new THREE.Vector3(PHASE_B[0], PHASE_B[1], PHASE_B[2]) }
  };

  var material = new THREE.ShaderMaterial({
    uniforms: uniforms,
    vertexShader: [
      'varying vec2 vUv;',
      'void main() { vUv = uv; gl_Position = vec4(position, 1.0); }'
    ].join('\n'),
    fragmentShader: [
      'precision highp float;',
      'uniform sampler2D uTex, uDepth, uFlow;',
      'uniform sampler2D uL0, uL1, uL2, uL3, uL4, uL5;',
      'uniform float uTime, uScreenAspect, uImageAspect, uAssets;',
      'uniform float uFlowAmp, uParallax, uFlowDecode;',
      'uniform vec2 uMouse, uImgSize;',
      'uniform vec3 uPhaseA, uPhaseB;',
      'varying vec2 vUv;',

      /* Letterbox (contain) mapping: the FULL painting always stays visible and
         undistorted; leftover viewport area becomes black bars. */
      'vec3 containUV(vec2 uv) {',
      '  if (uScreenAspect > uImageAspect) {',
      '    float f = uImageAspect / uScreenAspect;',
      '    float x = (uv.x - 0.5) / f + 0.5;',
      '    return vec3(x, uv.y, step(0.0, x) * step(x, 1.0));',
      '  } else {',
      '    float f = uScreenAspect / uImageAspect;',
      '    float y = (uv.y - 0.5) / f + 0.5;',
      '    return vec3(uv.x, y, step(0.0, y) * step(y, 1.0));',
      '  }',
      '}',

      'void main() {',
      '  vec3 m = containUV(vUv);',
      '  vec2 uv = clamp(m.xy, 0.0, 1.0);',
      '  float inside = m.z;',

      /* gentle global breathing (subtle zoom, both modes) */
      '  uv = (uv - 0.5) * (1.0 - 0.012 * sin(uTime * 0.45)) + 0.5;',

      '  vec3 col;',
      '  if (uAssets >= 0.5) {',
      /* ---- NEURAL MODE ---- */
      '    float wSky  = texture2D(uL0, uv).r;',
      '    float wMoon = texture2D(uL1, uv).r;',
      '    float wStar = texture2D(uL2, uv).r;',
      '    float wCyp  = texture2D(uL3, uv).r;',
      '    float wVil  = texture2D(uL4, uv).r;',
      '    float wMtn  = texture2D(uL5, uv).r;',

      /* per-layer temporal phase: the six weights partition the image, so this
         is a smoothly interpolated phase field (no lockstep motion) */
      '    float phase = dot(vec3(wSky, wMoon, wStar), uPhaseA)',
      '                + dot(vec3(wCyp, wVil, wMtn), uPhaseB);',

      /* MiDaS depth: pointer parallax + slow autonomous drift */
      '    float depth = texture2D(uDepth, uv).r;',
      '    vec2 par = (uMouse - 0.5) * (depth - 0.35) * uParallax;',
      '    par += vec2(sin(uTime * 0.31), cos(uTime * 0.27)) * 0.016 * depth;',

      /* RAFT flow advection (v4: comprehensive field — every region moves),
         pulsed per-layer out of phase */
      '    vec2 fpx = (texture2D(uFlow, uv).rg - 0.5) * uFlowDecode;',
      '    vec2 fuv = fpx / uImgSize;',
      '    float pulse = sin(uTime * 0.9 + phase) * 0.65',
      '                + sin(uTime * 0.23 + 1.7) * 0.35;',

      /* procedural Van Gogh wave — blended on top of the neural flow so the
         whole canvas keeps breathing even where RAFT underestimates */
      '    vec2 proc;',
      '    proc.x = sin(uv.y * 16.0 + uTime * 0.8',
      '               + sin(uv.x * 7.0 + uTime * 0.3) * 1.3) * 0.0040;',
      '    proc.y = sin(uv.x * 12.0 - uTime * 0.6 + uv.y * 5.0) * 0.0022;',
      '    float procW = 0.35 + 0.65 * (wSky + wStar * 0.5);',

      '    vec2 adv = fuv * pulse * uFlowAmp',
      '             + proc * procW * (0.45 + 0.55 * pulse);',

      '    vec2 uvN = uv + par + adv;',
      '    col = texture2D(uTex, clamp(uvN, 0.0, 1.0)).rgb;',

      /* star twinkle */
      '    col += wStar * (0.08 + 0.08 * sin(uTime * 2.6 + uv.x * 37.0));',
      /* village window flicker (bright pixels only) */
      '    float lum = dot(col, vec3(0.299, 0.587, 0.114));',
      '    col += wVil * smoothstep(0.30, 0.65, lum)',
      '         * 0.14 * (0.5 + 0.5 * sin(uTime * 3.7 + uv.x * 211.0));',
      /* moon glow breathing */
      '    col += wMoon * 0.05 * (0.5 + 0.5 * sin(uTime * 0.9 + 1.0));',
      '  } else {',
      /* ---- FALLBACK MODE (procedural, no assets) ---- */
      '    vec2 w;',
      '    w.x = sin(uv.y * 24.0 + uTime * 1.2) * 0.0028',
      '        + sin(uv.y * 7.0  - uTime * 0.7) * 0.0018;',
      '    w.y = cos(uv.x * 20.0 + uTime * 0.9) * 0.0016;',
      '    col = texture2D(uTex, clamp(uv + w, 0.0, 1.0)).rgb;',
      '    col *= 1.0 + 0.02 * sin(uTime * 0.8);',
      '  }',

      '  gl_FragColor = vec4(col * inside, 1.0);',  // bars stay pure black
      '}'
    ].join('\n')
  });

  scene.add(new THREE.Mesh(new THREE.PlaneGeometry(2, 2), material));

  /* ---------- status badge (self-fading, deployment self-check) ---------- */
  var badge = document.createElement('div');
  badge.id = 'vg-badge';
  Object.assign(badge.style, {
    position: 'fixed', left: '12px', bottom: '12px', zIndex: '10',
    fontFamily: 'ui-monospace, SFMono-Regular, Consolas, monospace',
    fontSize: '11px', lineHeight: '1.55', padding: '6px 10px',
    borderRadius: '4px', color: '#fff', background: 'rgba(0,0,0,0.55)',
    borderLeft: '3px solid #888', pointerEvents: 'none',
    maxWidth: '70vw', opacity: '0', transition: 'opacity 1.2s ease'
  });
  document.body.appendChild(badge);

  function showBadge(neuralOn, detail) {
    badge.style.borderLeftColor = neuralOn ? '#4ade80' : '#fbbf24';
    badge.innerHTML = neuralOn
      ? 'NEURAL PIPELINE: ACTIVE<br><span style="opacity:.75">' +
        'MiDaS depth + RAFT flow + 6 SAM layers</span>'
      : 'NEURAL PIPELINE: NOT LOADED<br><span style="opacity:.75">' +
        'procedural fallback active — ' + detail + '</span>';
    badge.style.opacity = '1';
    setTimeout(function () { badge.style.opacity = '0'; }, 9000);
  }

  /* ---------- asset loading with failure tracking ---------- */
  var failedFiles = [];
  var manager = new THREE.LoadingManager(
    function () {                                   // onLoad: queue settled
      var neuralOn = failedFiles.length === 0;
      uniforms.uAssets.value = neuralOn ? 1.0 : 0.0;
      window.__vanGoghStatus = { mode: neuralOn ? 'neural' : 'fallback',
                                 failed: failedFiles.slice() };
      if (neuralOn) {
        console.info('[VanGogh] neural mode active: depth + flow + 6 layers loaded');
      } else {
        console.warn('[VanGogh] neural assets missing (' + failedFiles.length +
                     '), running procedural fallback. Missing:', failedFiles);
      }
      showBadge(neuralOn, failedFiles.length + ' asset file(s) missing');
    },
    undefined,
    function (url) { failedFiles.push(url); }       // onError: record the URL
  );
  var loader = new THREE.TextureLoader(manager);

  function dataTex(url) {   // data textures: no mipmaps, clamp edges, linear filter
    var t = loader.load(url);
    t.generateMipmaps = false;
    t.minFilter = THREE.LinearFilter;
    t.magFilter = THREE.LinearFilter;
    t.wrapS = t.wrapT = THREE.ClampToEdgeWrapping;
    return t;
  }

  uniforms.uTex.value = loader.load('starry-night.jpg');
  uniforms.uTex.value.colorSpace = THREE.SRGBColorSpace;
  uniforms.uDepth.value = dataTex('cv_pipeline/assets/depth/depth_midas_small.png');
  uniforms.uFlow.value = dataTex('cv_pipeline/assets/flow/flow_raft_rgb.png');
  ['uL0', 'uL1', 'uL2', 'uL3', 'uL4', 'uL5'].forEach(function (k, i) {
    uniforms[k].value = dataTex(LAYER_FILES[i]);
  });

  /* ---------- interaction ---------- */
  var mouseTarget = new THREE.Vector2(0.5, 0.5);
  window.addEventListener('pointermove', function (e) {
    mouseTarget.set(e.clientX / window.innerWidth, 1.0 - e.clientY / window.innerHeight);
  }, { passive: true });

  function resize() {
    var w = window.innerWidth, h = window.innerHeight;
    renderer.setSize(w, h, false);
    uniforms.uScreenAspect.value = w / h;
  }
  window.addEventListener('resize', resize);
  resize();

  /* ---------- render loop ---------- */
  var t0 = performance.now();
  (function animate(now) {
    uniforms.uTime.value = (now - t0) * 0.001;
    uniforms.uMouse.value.lerp(mouseTarget, 0.08);   // smooth pointer
    renderer.render(scene, camera);
    requestAnimationFrame(animate);
  })(t0);
})();
